# Generated by Django 5.0.3 on 2024-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/targets'),
        ),
    ]
