# Generated by Django 5.0.3 on 2024-04-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additionallyuser', '0002_alter_country_name'),
        ('user', '0007_remove_customuser_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cityis',
        ),
    ]
