# Generated by Django 5.0.3 on 2024-04-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionallyuser', '0001_initial'),
        ('user', '0002_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additionallyuser.country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additionallyuser.language'),
        ),
    ]
